In [1]:
# Numpy's array class is called ndarray

# ndarray.ndim
# ndarray.shape
# ndarray.size
# ndaray.dtype
# ndarray.itemsize
# ndarray.data

In [2]:
import numpy as np

a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int32'

In [6]:
a.itemsize

4

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

In [11]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [12]:
a.dtype

dtype('int32')

In [13]:
b = np.array([1.2, 3.5, 5.11])
b.dtype

dtype('float64')

In [14]:
# WRONG a = np.array(1, 2, 3, 4)
a = np.array([1, 2, 3, 4])  #RIGHT

In [15]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [16]:
c = np.array([[1, 2], [3, 4]], dtype = complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [17]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [18]:
np.ones((2, 3, 4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [19]:
np.empty((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [22]:
np.arange(0, 2, 0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [23]:
from numpy import pi

np.linspace(0, 2, 9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [24]:
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)

In [25]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [26]:
b = np.arange(12).reshape(4, 3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [27]:
c = np.arange(24).reshape(2, 3, 4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [28]:
print(np.arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [1]:
import numpy as np

print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [33]:
# np.set_printoptions(threshold = 'nan')

In [7]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [9]:
c = a - b
c

array([20, 29, 38, 47])

In [10]:
b**2

array([0, 1, 4, 9])

In [11]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [12]:
a < 35

array([ True,  True, False, False], dtype=bool)

In [13]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
A*B

array([[2, 0],
       [0, 4]])

In [14]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [15]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])