In [1]:
import numpy as np
from numpy import newaxis

In [3]:
a = np.floor(10 * np.random.random((2, 2)))
b = np.floor(10 * np.random.random((2, 2)))

In [4]:
np.column_stack((a, b))

array([[ 1.,  5.,  9.,  8.],
       [ 7.,  2.,  0.,  9.]])

In [5]:
a = np.array([4., 2.])
b = np.array([2., 8.])
a[:, newaxis]

array([[ 4.],
       [ 2.]])

In [6]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [7]:
np.vstack((a[:, newaxis], b[:, newaxis]))

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

In [8]:
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

In [9]:
a = np.floor(10 * np.random.random((2, 12)))
a

array([[ 8.,  6.,  5.,  6.,  9.,  7.,  5.,  3.,  1.,  8.,  6.,  1.],
       [ 9.,  2.,  2.,  4.,  7.,  1.,  1.,  6.,  1.,  1.,  0.,  3.]])

In [10]:
np.hsplit(a, 3)

[array([[ 8.,  6.,  5.,  6.],
        [ 9.,  2.,  2.,  4.]]), array([[ 9.,  7.,  5.,  3.],
        [ 7.,  1.,  1.,  6.]]), array([[ 1.,  8.,  6.,  1.],
        [ 1.,  1.,  0.,  3.]])]

In [12]:
np.hsplit(a, (3, 4))

[array([[ 8.,  6.,  5.],
        [ 9.,  2.,  2.]]), array([[ 6.],
        [ 4.]]), array([[ 9.,  7.,  5.,  3.,  1.,  8.,  6.,  1.],
        [ 7.,  1.,  1.,  6.,  1.,  1.,  0.,  3.]])]