In [1]:
import numpy as np
from numpy import newaxis

In [3]:
a = np.floor(10 * np.random.random((2, 2)))
b = np.floor(10 * np.random.random((2, 2)))

In [4]:
np.column_stack((a, b))

array([[ 1.,  5.,  9.,  8.],
       [ 7.,  2.,  0.,  9.]])

In [5]:
a = np.array([4., 2.])
b = np.array([2., 8.])
a[:, newaxis]

array([[ 4.],
       [ 2.]])

In [6]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [7]:
np.vstack((a[:, newaxis], b[:, newaxis]))

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

In [8]:
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

In [9]:
a = np.floor(10 * np.random.random((2, 12)))
a

array([[ 8.,  6.,  5.,  6.,  9.,  7.,  5.,  3.,  1.,  8.,  6.,  1.],
       [ 9.,  2.,  2.,  4.,  7.,  1.,  1.,  6.,  1.,  1.,  0.,  3.]])

In [10]:
np.hsplit(a, 3)

[array([[ 8.,  6.,  5.,  6.],
        [ 9.,  2.,  2.,  4.]]), array([[ 9.,  7.,  5.,  3.],
        [ 7.,  1.,  1.,  6.]]), array([[ 1.,  8.,  6.,  1.],
        [ 1.,  1.,  0.,  3.]])]

In [12]:
np.hsplit(a, (3, 4))

[array([[ 8.,  6.,  5.],
        [ 9.,  2.,  2.]]), array([[ 6.],
        [ 4.]]), array([[ 9.,  7.,  5.,  3.,  1.,  8.,  6.,  1.],
        [ 7.,  1.,  1.,  6.,  1.,  1.,  0.,  3.]])]

In [2]:
a = np.arange(12)
b = a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
b is a

True

In [4]:
b.shape = 3, 4
a.shape

(3, 4)

In [5]:
def f(x):
    print(id(x))
    
id(a)

56865560

In [6]:
f(a)

56865560


In [7]:
c = a.view()

In [8]:
c is a

False

In [9]:
c.base is a

True

In [11]:
c.flags.owndata

False

In [12]:
c.shape = 2, 6
a.shape

(3, 4)

In [14]:
c[0, 4] = 1234

In [15]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [17]:
s = a[ : , 1:3]
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [18]:
d = a.copy()

In [19]:
d is a

False

In [20]:
d.base is a

False

In [21]:
d[0, 0] = 9999

In [22]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [24]:
a = np.arange(12) ** 2
i = np.array([1, 1, 3, 8, 5])
a[i]

array([ 1,  1,  9, 64, 25])

In [25]:
j = np.array([[3, 4], [9, 7]])
a[j]

array([[ 9, 16],
       [81, 49]])

In [26]:
palette = np.array([[0, 0, 0],
                    [255, 0, 0],
                    [0, 255, 0],
                    [0, 0, 255],
                    [255, 255, 255]])
image = np.array([[0, 1, 2, 0], [0, 3, 4, 0]])
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [22]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
i = np.array([[0, 1], [1, 2]])
j = np.array([[2, 1], [3, 3]])
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [29]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [30]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [31]:
l = [i, j]
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [32]:
s = np.array([i, j])
a[s]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [33]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

In [34]:
time = np.linspace(20, 145, 5)
data = np.sin(np.arange(20)).reshape(5, 4)

In [35]:
time

array([  20.  ,   51.25,   82.5 ,  113.75,  145.  ])

In [36]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [37]:
ind = data.argmax(axis = 0)

In [38]:
ind

array([2, 0, 3, 1], dtype=int32)

In [39]:
time_max = time[ind]

In [43]:
data_max = data[ind, range(data.shape[1])]

In [44]:
time_max

array([  82.5 ,   20.  ,  113.75,   51.25])

In [45]:
data_max

array([ 0.98935825,  0.84147098,  0.99060736,  0.6569866 ])

In [46]:
np.all(data_max == data.max(axis = 0))

True

In [47]:
a = np.arange(5)

In [48]:
a[[0, 0, 2]] = [1, 2, 3]

In [49]:
a

array([2, 1, 3, 3, 4])

In [50]:
a = np.arange(5)

In [51]:
a[[0, 0, 2]] += 1

In [52]:
a

array([1, 1, 3, 3, 4])

In [53]:
a = np.arange(12).reshape(3, 4)

In [54]:
b = a > 4

In [55]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [56]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [57]:
a[b] = 0

In [58]:
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [59]:
import matplotlib.pyplot as plt

In [61]:
def mandelbrot(h, w, maxit = 20):
    y, x = np.ogrid[-1.4 : 1.4 : h * 1j, -2 : 0.8 : w * 1j]
    c = x + y * 1j
    z = c
    divtime = maxit + np.zeros(z.shape, dtype = int)
    
    for i in range(maxit):
        z = z ** 2 + c
        diverge = z * np.conj(z) > 2 ** 2
        div_now = diverge & (divtime == maxit)
        divtime[div_now] = i
        z[diverge] = 2
        
    return divtime
plt.imshow(mandelbrot(400, 400))
plt.show()

In [62]:
a = np.arange(12).reshape(3, 4)
b1 = np.array([False, True, True])
b2 = np.array([True, False, True, False])

In [63]:
a[b1, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
a[b1]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
a[:, b2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [66]:
a[b1, b2]

array([ 4, 10])

In [2]:
a = np.array([2, 3, 4, 5])
b = np.array([8, 5, 4])
c = np.array([5, 4, 6, 8, 3])
ax, bx, cx = np.ix_(a, b, c)
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [3]:
bx

array([[[8],
        [5],
        [4]]])

In [4]:
cx

array([[[5, 4, 6, 8, 3]]])

In [5]:
ax.shape

(4, 1, 1)

In [6]:
bx.shape

(1, 3, 1)

In [7]:
cx.shape

(1, 1, 5)

In [8]:
result = ax + bx * cx
result

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

In [9]:
result[3, 2, 4]

17

In [10]:
a[3] + b[2] * c[4]

17

In [12]:
def ufunc_reduce(ufct, *vectors):
    vs = np.ix_(*vectors)
    r = ufct.identity
    for v in vs:
        r = ufct(r, v)
    return r
ufunc_reduce(np.add, a, b, c)

array([[[15, 14, 16, 18, 13],
        [12, 11, 13, 15, 10],
        [11, 10, 12, 14,  9]],

       [[16, 15, 17, 19, 14],
        [13, 12, 14, 16, 11],
        [12, 11, 13, 15, 10]],

       [[17, 16, 18, 20, 15],
        [14, 13, 15, 17, 12],
        [13, 12, 14, 16, 11]],

       [[18, 17, 19, 21, 16],
        [15, 14, 16, 18, 13],
        [14, 13, 15, 17, 12]]])

In [29]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[ 1.  2.]
 [ 3.  4.]]


In [15]:
a.transpose()

array([[ 1.,  3.],
       [ 2.,  4.]])

In [16]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [17]:
u = np.eye(2)

In [18]:
u

array([[ 1.,  0.],
       [ 0.,  1.]])

In [30]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

In [31]:
np.dot(i, j)

array([[ 1.,  0.],
       [ 2., -1.]])

In [32]:
np.trace(u)

2.0

In [33]:
y = np.array([[5.], [7.]])

In [34]:
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [35]:
np.linalg.eig(j)

(array([ 0.+1.j,  0.-1.j]),
 array([[ 0.70710678+0.j        ,  0.70710678-0.j        ],
        [ 0.00000000-0.70710678j,  0.00000000+0.70710678j]]))