In [1]:
# Numpy's array class is called ndarray

# ndarray.ndim
# ndarray.shape
# ndarray.size
# ndaray.dtype
# ndarray.itemsize
# ndarray.data

In [2]:
import numpy as np

a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int32'

In [6]:
a.itemsize

4

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

In [11]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [12]:
a.dtype

dtype('int32')

In [13]:
b = np.array([1.2, 3.5, 5.11])
b.dtype

dtype('float64')

In [14]:
# WRONG a = np.array(1, 2, 3, 4)
a = np.array([1, 2, 3, 4])  #RIGHT

In [15]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [16]:
c = np.array([[1, 2], [3, 4]], dtype = complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [17]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [18]:
np.ones((2, 3, 4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [19]:
np.empty((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [22]:
np.arange(0, 2, 0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [23]:
from numpy import pi

np.linspace(0, 2, 9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [24]:
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)

In [25]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [26]:
b = np.arange(12).reshape(4, 3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [27]:
c = np.arange(24).reshape(2, 3, 4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [28]:
print(np.arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [1]:
import numpy as np

print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [33]:
# np.set_printoptions(threshold = 'nan')

In [7]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [9]:
c = a - b
c

array([20, 29, 38, 47])

In [10]:
b**2

array([0, 1, 4, 9])

In [11]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [12]:
a < 35

array([ True,  True, False, False], dtype=bool)

In [13]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
A*B

array([[2, 0],
       [0, 4]])

In [14]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [15]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [1]:
import numpy as np

In [2]:
a = np.ones((2, 3), dtype = int)
b = np.random.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [3]:
b += a

In [4]:
b

array([[ 3.18874434,  3.1281    ,  3.49136012],
       [ 3.13766185,  3.29633792,  3.07810158]])

In [5]:
a += b
a

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [8]:
from numpy import pi

a = np.ones(3, dtype = np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [9]:
c = a + b
c

array([ 1.        ,  2.57079633,  4.14159265])

In [10]:
c.dtype.name

'float64'

In [11]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [12]:
d.dtype.name

'complex128'

In [13]:
a = np.random.random((2, 3))
a

array([[ 0.31158505,  0.80540152,  0.40279851],
       [ 0.67199556,  0.16017672,  0.80547557]])

In [14]:
a.sum()

3.1574329362227722

In [15]:
a.min()

0.16017672214119894

In [16]:
a.max()

0.80547557462785135

In [17]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
b.sum(axis = 0) # sum of each column

array([12, 15, 18, 21])

In [19]:
b.min(axis = 1) # min of each row

array([0, 4, 8])

In [20]:
b.cumsum(axis = 1) # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [21]:
b.min(axis = 0)

array([0, 1, 2, 3])

In [22]:
b.cumsum(axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [23]:
B = np.arange(3)

In [24]:
B

array([0, 1, 2])

In [25]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [26]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [27]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([ 2.,  0.,  6.])

In [1]:
import numpy as numpy

In [1]:
import numpy as np

In [2]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [3]:
a[2]

8

In [4]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [5]:
a[:6:2]

array([ 0,  8, 64], dtype=int32)

In [6]:
a[:6:2] = -1000

In [7]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729], dtype=int32)

In [9]:
a[ : : -1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000], dtype=int32)

In [10]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


E:\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: invalid value encountered in power
  from ipykernel import kernelapp as app


In [10]:
def f(x, y):
    return 10 * x + y

In [11]:
b = np.fromfunction(f, (5, 4), dtype = int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [12]:
b[2, 3]

23

In [13]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [14]:
b[ : , 1]

array([ 1, 11, 21, 31, 41])

In [15]:
b[1:3, 1]

array([11, 21])

In [16]:
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [17]:
b[-1]

array([40, 41, 42, 43])

In [18]:
c = np.array([[[0, 1, 2],
               [0, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape

(2, 2, 3)

In [19]:
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [20]:
c[1, : , : ]

array([[100, 101, 102],
       [110, 112, 113]])

In [21]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [22]:
c[ : , : , 2]

array([[  2,  13],
       [102, 113]])

In [23]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [24]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [25]:
a = np.floor(10 * np.random.random((3, 4)))
a

array([[ 5.,  2.,  2.,  4.],
       [ 4.,  0.,  6.,  0.],
       [ 9.,  6.,  8.,  6.]])

In [27]:
a.shape

(3, 4)

In [28]:
a.ravel()

array([ 5.,  2.,  2.,  4.,  4.,  0.,  6.,  0.,  9.,  6.,  8.,  6.])

In [29]:
a.shape = (6, 2)

In [30]:
a.T

array([[ 5.,  2.,  4.,  6.,  9.,  8.],
       [ 2.,  4.,  0.,  0.,  6.,  6.]])

In [31]:
a

array([[ 5.,  2.],
       [ 2.,  4.],
       [ 4.,  0.],
       [ 6.,  0.],
       [ 9.,  6.],
       [ 8.,  6.]])

In [32]:
a.resize((2, 6))
a

array([[ 5.,  2.,  2.,  4.,  4.,  0.],
       [ 6.,  0.,  9.,  6.,  8.,  6.]])

In [33]:
a.reshape(3, -1)

array([[ 5.,  2.,  2.,  4.],
       [ 4.,  0.,  6.,  0.],
       [ 9.,  6.,  8.,  6.]])

In [34]:
a = np.floor(10 * np.random.random((2, 2)))
a

array([[ 1.,  0.],
       [ 3.,  9.]])

In [35]:
b = np.floor(10 * np.random.random((2, 2)))
b

array([[ 2.,  8.],
       [ 7.,  4.]])

In [36]:
np.vstack((a, b))

array([[ 1.,  0.],
       [ 3.,  9.],
       [ 2.,  8.],
       [ 7.,  4.]])

In [37]:
np.hstack((a, b))

array([[ 1.,  0.,  2.,  8.],
       [ 3.,  9.,  7.,  4.]])